language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: shareyourideas-nodejs
  api_key:
    secure: cipEtyn5h368mUFhAqYPSo+zWwQxU2mqSLCJFZOxp/pAhkSS7yZriwqCH3cPysnIx2KYUZvLZYFYBJldSMv9kQm6dGu3e4W1yMLYy6w5PoWjOSQvsHPy+OcUONj/wUb/2788MPWYXWdXX6VlgEUySKibuRWm9aSGwn1UsCN3egrixqa8PumyHGgKR1JB02LDi24d4BVaN27gor5i5IWHFG+WD6hFjxVcq0xp5H7belfcSOCIlz4cSCiBgKTCqucHqt0GRtLQ+AOGXLi9C7AtnXdP4KhBBTs/N30q6axC3IMUV3c3xJk3Bq56hQow0//5nFsndTpU5JddFKswaa7D2c0Gsx6FgPL3Qj+c79YYVyHoxzxspF6zOjR+pVvU8gdyihAA43fI6hjICXk13xX3TJn26lSehCiHaDbLA23moA7/JvLyf/x6WqolAgzvPKAr7E4feVx44bn4OpCcJ5LzDHKdLPkBxGkd8BGa0CzXti9OW8F6zcCjBh0fqLlbftXPi6MqGYHeGysFYOk3jryVa5pheMzVs18pNfg9/qEcEtFCLZ6aUyTn4YH6D39bZ8K86zyivwwgqYWfuEMJ38ThDBmh2f4CvExHqCkE3neDN6qfQuFGRUuGqAsqtnkrgGVtG16DaPsoIWGbFP3Hw5LCf+or6oacKkH6wGICLDZ6wMw=
