language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: heroku-shareyoutii
  api_key:
    secure: Vl8J9uEYaqmlzVJGLQlHx129+8tSW4KuZuB15l1Z6tPBN4MO6Udvg4w53molEBfGLmrih0OZmrcyUVav1qH0eroCWPP2Yv2KKH07JNqmSz4L+uH/0wmtfD8ia6lnAKj4v3ama2va1pSF87lr3K4qvoCAVee4mmI+78A0/y2W0dt0IuA0jQFBSJ/LxXiJ5H5h2OJmB9sswnOYkFAawNATl/S6QdsXZseyxct3IDGv+Bi0rf/RJyWeS9IQL3qCKKFQVUJtMFnyDVcXIsuK71f85WHRbnA52hUbGdz6+US73j4RVowKwN4yQTa/sJtw86f7VzIshYyXVKqCz0yGBzU8IYt9smcfXz5OrUgYcHDzgg/HugvHM85eZG9V4wI4tYM9FsjPHnfIGbR8rLvS3HoEZgz7YvhvyB7txRMYFf4rqZNM/donG2E1LM2Rs6xVbPZYZUYrTiZvYzgb7R5GX6VvSIK4JFLDNPU4OpXFd18VqcqJ8Twq3Nu3DGhUZixPpl8jKqonEPup/0LGrjuc0Qmjc0cTxo0SC04HVIvlJPIpZqxQrryHu4lmTK9+HmGBSgzVgLc204D2bNioAMxvvwJRNuYovf/W12lR8P+6/E/4XSWlp7wZ1zPRb5PTiEPSKNKQfe9xb7v757Af1vG3JWKl7oCPKVyZxdFVtarkl5zNMpw=
