language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: heroku-shareyoutii
  api_key:
    secure: rWb9M6eTsO1TYgsA/WI5Gw+aHdSESsuI9EvrHHPa+4pH7fuevLZx1XrW8gN7WXHajsdo9UjVaZ3mPn6vE7+Rc1npN/SLdRWcq6+MYyngAEAEvuyuCQYc1ktiTgxLZOndU92roDHsAE0+W5N86SX+UhXC94VU5L+xp0LNMLeLxqenKirp+W3hafzLdcXUEzFMS/CMdRgknrNaJwP8VyNHzkUyyZZ3kInDBccjdMu/WR5+feLU3kzedm/hcu4t7Y+uj9haYbfZKJ0Lq0A5CEqBMl6x7Z1iNkUT0lfZSpbPqcutrVhhUa0qiVE7Tk89iwBjgmuZY4tZRuarMpfwzB2FhJzrjdN+4KEoxPxv5xBTIQwuZ0WQfWV2cP1t3ANrZ2g5sOoE1AQJFmC3ZyGR6cV0MOK0ziYeAs7HiozlcqPhG2E8w4q+AjPedOl5rZRBf25CT91n7M29OpoMsSULbzZ/mB7Y4FO8KbA7syWXUGm1JwkUJg+KGxa0aKUjTT5al37HDu15rMpUFGJqkGtTuMul33Uq6QNFcj0b7S6bwouD8gkDyOAOh+ByWw9Xdkow0JoST79Pc6VU0ye3+EG33+ljzOAdMDcoJlPHUfojDmdGFWJimMX9AxPwEFRp7zIKGM5cUac9XqAH9y/5aHbDQ/iATcVlJIy35pAM8F0ZzZp9HvY=
