language: node_js
node_js:
  - "stable"
deploy:
  provider: heroku
  app: heroku-shareyoutii
  api_key:
    secure: KE8/s7mk0Kzl4b8kBFBG7HLqMCfEil+t8pooUBLn/1TpQvKvcUE3tVvjmoGE1FyX+BaImE8AY5WB7V+cBRBPW6mc6mPLVVaZT/2eUDb4vN4oEXpqKXM7njqEgmpc0ldJZjSRhyQ+oSvYX7QVG27u76uCwdSxYMm0nu7xdoLjMnq/g4gJvH1rQQOtYIEYXwA2MPYvNGEAeudoctsJyRXWkaXKLju1qCAHltmxvVs8f6o9ELKfj1GOL07mQ0bUoGtD7LC5+I5pG5ljoKuqNPUpm3/wcQQiraLBBCLN2L1STL/0HQ19PPkPEw5a6kDslhA91jYxQneLkNx3keMR/QlUHoJDJ45Q6Ln+hn8CWLQKVQbYMbNguh81Rh7M95pbRVvWlXySJ+hyFgemmbBxUceMFH799FN1PLHftQbTM1VP8v6cgERYE7hZST9e2PRg8xo6R5mmZxGkBD4RGXXVOQeLu2ZvAmIc3cRhxuS1FhM2DhAjVazJ3AJVXx0v/WPpe4CacUOWHu1rIYfW14ZY4tMPGPYHAoTXMxdSkAzgctAcV/eNh2kIm4FNgS/M7S1Bpu7T4Llx1H2uoxd9SJxMbwUSn0LAdudCp0gOErJFJC1jCmcOIKPn7uPnisOHHydefw3pJp7SeL39St+BfQ/lsQBzyQ0EHRB+BEIB/TZQQtqMY9Y=
